baseURL = 'https://blog.wasd.fi'
languageCode = 'en-uk'
title = 'Wasd blog'
theme = 'hugo-blog-awesome'
sectionPagesMenu = 'main'
[params]
  subtitle = 'The Best Widgets on Earth'
  [params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-1212'

[[params.socialIcons]]
name = "github"
url = "https://github.com/msrn"

[[params.socialIcons]]
name = "email"
url = "blog@wasd.fi"


defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.fi]
    contentDir = 'content/fi'
    disabled = false
    languageCode = 'fi-FI'
    languageDirection = 'ltr'
    languageName = 'Suomi'
    title = 'Wasd ploki'
    weight = 1
    [languages.fi.params]
      subtitle = 'sivusto'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-UK'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Wasd blog'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'

