baseURL = 'https://blog.wasd.fi'
languageCode = 'en-uk'
title = 'Wasd blog'
theme = 'hugo-blog-awesome'

[[params.socialIcons]]
name = "github"
url = "https://github.com/msrn"

[[params.socialIcons]]
name = "email"
url = "blog@wasd.fi"
