baseURL = 'https://blog.wasd.fi'
languageCode = 'en-uk'
title = 'Wasd blog'
theme = 'anubis2'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true






[languages]
  [languages.fi]
    contentDir = 'content/fi'
    disabled = false
    languageCode = 'fi-FI'
    languageDirection = 'ltr'
    languageName = 'Suomi'
    title = 'Wasd ploki'
    weight = 1

  [languages.fi.menus]
    [[languages.fi.menus.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Koti'
    weight = 10
    [[languages.fi.menus.main]]
    pageRef="/about"
    name = 'Tietoa'
    weight = 20
    [[languages.fi.menus.main]]
    pageRef="/categories"
    name = 'Aiheet'
    weight = 30

  [languages.fi.params]
    subtitle = 'sivusto'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-UK'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Wasd blog'
    weight = 2

    [languages.en.menus]
    [[languages.en.menus.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    weight = 10
    [[languages.en.menus.main]]
    pageRef="/about"
    name = 'About'
    weight = 20
    [[languages.en.menus.main]]
    pageRef="/categories"
    name = 'Categories'
    weight = 30
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'

